Added Dutch (nl) localization
coteditor/CotEditor pull request #1611
Opened 2024-04-07 13:10 UTC by yasingunaydiin

I'm still working on it but I'll do my best to finish it as soon as possible.

2024-04-07 13:24 UTC, 1024jp commented
Thank you for your PR.
I confirmed that the changes seem correctly pushed this time.
You have so far done 6 .xcstrings files, correct?

Keep on and let me know if all finished.

2024-04-07 13:25 UTC, yasingunaydiin commented
Correct!

Now i can work in peace hah. Thank you for your patience!

[image: user img]
Yasin Günaydın
Localization Specialist/ Interpreter Dutch & Turkish

   - [image: Mobile icon] Mobile: +905417688751


   - [image: linkedIn icon]
<https://www.linkedin.com/in/yasin-gunaydin-b45466204/>



Op zo 7 apr 2024 om 16:24 schreef 1024jp ***@***.***>

> Thank you for your PR.
> I confirmed that the changes seem correctly pushed this time.
> You have so far done 6 .xcstrings files, correct?
>
> Keep on and let me know if all finished.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/coteditor/CotEditor/pull/1611#issuecomment-2041471225>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATQVCUMB6OE5ZQDY3AEMLITY4FCJ7AVCNFSM6AAAAABF3KHMUSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANBRGQ3TCMRSGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-04-12 14:33 UTC, 1024jp commented
@yasingunaydiin Hi, this is a reminder in case you may not have noticed that there are some localizable files also in the Storyboard section. Toggle the chevrons of each storyboard and you'll find them.

<img width="1552" alt="Screenshot 2024-04-12 at 23 30 17" src="https://github.com/coteditor/CotEditor/assets/1165044/a07f87c1-55ab-46dd-ae3e-3b6761116c11">

Meanwhile, I'll review your work in the Localizable section.

2024-04-12 16:06 UTC, 1024jp requested changes
I've reviewed all the localized strings until this point and found some potential strings that could be improved. I'll suggest them later when all the strings are once localized.

But at this point, I would like to share the following two points with you:
- Please consider updating the string I mentioned.
- The pair of double quotation marks in English seems to be localized to straight quotation marks in Dutch in macOS. For instance, `“%@”` will be `'%@'` in Dutch. (For those that have already been localized, I can convert them by myself. Just please be careful about what you are going to localize.)

2024-04-12 16:06 UTC, 1024jp commented on CotEditor/mul.lproj/Document.xcstrings
> +            "value" : "Selectie selecteren of verwijderen  "
You perhaps misinterpreted the original string. The original string, "Comment-out or uncomment selection," is the tooltip for the Comment toolbar item that either add or remove comment delimiters to/from the selection.

2024-04-12 16:07 UTC, 1024jp commented
> Yes im currently working on them and am almost done with them.

Thank you! I realized I was a bit impatient.

2024-04-12 17:09 UTC, yasingunaydiin commented on CotEditor/mul.lproj/Document.xcstrings
> +            "value" : "Selectie selecteren of verwijderen  "
Will look into it. I remember I had a hard time translating this so I looked at the German and Turkish translation for hints.

2024-04-13 03:31 UTC, 1024jp approved these changes

2024-04-13 07:50 UTC, merged

2024-04-13 08:07 UTC, 1024jp commented
Thank you! Perfect!

I've merged the changes and released CotEditor 4.8.0-rc so that you can check the actual implementation easily.
Please check for any oddities.
https://github.com/coteditor/CotEditor/releases/tag/4.8.0-rc

In addition, I have made some improvements on my end to use macOS-specific expressions.
I don't think there are grammatical problems, but it would be helpful if you could confirm also this change just in case.
https://github.com/coteditor/CotEditor/commit/692b764056053ce540bc5a564201095e60635360

Once all issues in this 4.8.0-rc are fixed, I will release the official version by the end of this month.